import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest) {
  try {
    const liveTrendingData = [
      {
        id: 'trend_screen_zoom_reaction',
        title: '📱 "Look At My Screen (Live Zoom)"',
        platform: 'SaaSReels #1 Converting Format',
        viewsMetric: '18.4M Views (Live Trend)',
        velocity: '14.2% Direct Signup CTR',
        soundtrack: 'Upbeat Tech Energy Bassline (TikTok Original)',
        soundtrackId: 'reels_audio_192837',
        category: 'split_demo',
        hookFormula: 'Wait, stop scrolling! Look at my screen right now. I just pasted my URL into [PRODUCT_NAME] and watch what happens in 3, 2, 1... It literally handles everything on autopilot.',
        previewThumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#saasdemo', '#aitools', '#usefulwebsites', '#saasreels', '#fyp'],
        soundBpm: 128,
        retentionScore: 99,
        viralAngle: 'live_demo_reaction',
      },
      {
        id: 'trend_podcast_host_secret',
        title: '🎙️ "The Leaked Podcast Epiphany"',
        platform: 'TikTok & Reels FYP #1 Authority',
        viewsMetric: '12.8M Views (Live Trend)',
        velocity: '+168% Full Watch-Through',
        soundtrack: 'Suspense Cinematic Ambient (Original Studio Audio)',
        soundtrackId: 'tiktok_audio_738491028',
        category: 'podcast',
        hookFormula: 'Host: "What is the ONE cheat code website that feels illegal to know in 2026?"\nGuest: "Hands down, [PRODUCT_NAME]. It completely automated our [PAIN_POINT] in thirty seconds."',
        previewThumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#podcastclip', '#techhack', '#founder', '#productivity', '#secrets'],
        soundBpm: 120,
        retentionScore: 98,
        viralAngle: 'podcast_interview',
      },
      {
        id: 'trend_split_subway_gameplay',
        title: '🎮 "Split-Screen Kinetic Gameplay"',
        platform: 'TikTok Algorithm #1 Watch-Time Hack',
        viewsMetric: '22.1M Views (Live Trend)',
        velocity: '4.2x Average Completion Rate',
        soundtrack: 'Phonk Drill - Night Drive Beat (Viral Sound)',
        soundtrackId: 'tiktok_audio_89401283',
        category: 'split_gameplay',
        hookFormula: 'POV: You are still wasting 10 hours doing [PAIN_POINT] in 2026 when [PRODUCT_NAME] literally does it in one click.\nStop working like an intern and use the cheat code.',
        previewThumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#cheatcode', '#workhack', '#mindblown', '#developer', '#fyp'],
        soundBpm: 135,
        retentionScore: 99,
        viralAngle: 'pov_cheat_code',
      },
      {
        id: 'trend_why_nobody_talking',
        title: '🤫 "Why Is Nobody Talking About This?"',
        platform: 'TikTok FYP High-Curiosity Loop',
        viewsMetric: '16.7M Views (Live Trend)',
        velocity: '94% Hook Hold Rate (0-3s)',
        soundtrack: 'Secret Mystery Reveal Bass (TikTok Sound)',
        soundtrackId: 'tiktok_audio_49102847',
        category: 'split_demo',
        hookFormula: 'Why is NOBODY on TikTok talking about this? If you are struggling with [PAIN_POINT], [PRODUCT_NAME] just released their new AI engine and it changes everything.',
        previewThumbnail: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#aitools', '#secretwebsite', '#techtrend', '#growthhack', '#musthaves'],
        soundBpm: 124,
        retentionScore: 97,
        viralAngle: 'secret_discovery',
      },
      {
        id: 'trend_darkmode_tweet_roast',
        title: '🥊 "Controversial Competitor Roast"',
        platform: 'Instagram Reels & Twitter Viral',
        viewsMetric: '9.3M Views (Live Trend)',
        velocity: '11.4% Link-In-Bio CTR',
        soundtrack: 'Dramatic Orchestra Drop - Epic Reveal',
        soundtrackId: 'ig_audio_4910284',
        category: 'tweet_reveal',
        hookFormula: '"Hot take: If your company is paying $2,000/month for manual creators instead of [PRODUCT_NAME], your entire growth strategy is burning money."',
        previewThumbnail: 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#startuplife', '#techroast', '#hottake', '#saastools', '#viral'],
        soundBpm: 110,
        retentionScore: 96,
        viralAngle: 'competitor_roast',
      },
      {
        id: 'trend_gatekeeping_boss',
        title: '💼 "My Boss Doesn\'t Know I Use This"',
        platform: 'TikTok Work/Tech Top Performer',
        viewsMetric: '14.9M Views (Live Trend)',
        velocity: '88% Share-to-Friend Rate',
        soundtrack: 'Sneaky Lo-fi Groove (Viral Trend)',
        soundtrackId: 'tiktok_audio_1029384',
        category: 'split_demo',
        hookFormula: 'My boss thinks I spend forty hours a week doing [PAIN_POINT], but I literally use [PRODUCT_NAME] to finish everything in thirty seconds on complete autopilot.',
        previewThumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#quietquitting', '#workhack', '#worklife', '#productivityhacks'],
        soundBpm: 115,
        retentionScore: 98,
        viralAngle: 'pov_cheat_code',
      },
      {
        id: 'trend_apple_notes_confession',
        title: '📝 "Apple Notes Unreleased Cheat Sheet"',
        platform: 'TikTok FYP High-Saves & Bookmarks',
        viewsMetric: '8.7M Views (Live Trend)',
        velocity: '93% Save & Bookmark Rate',
        soundtrack: 'Lofi Midnight Rain Chill Beats',
        soundtrackId: 'tiktok_audio_3819028',
        category: 'apple_notes',
        hookFormula: 'Stop scrolling and bookmark this right now. Things every founder needs to stop doing in 2026:\n1. Hiring expensive agencies for [PAIN_POINT]\n2. Not using [PRODUCT_NAME]\n3. Thank me later.',
        previewThumbnail: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#notesapp', '#secrets', '#hacks', '#businessgrowth', '#saveforlater'],
        soundBpm: 85,
        retentionScore: 95,
        viralAngle: 'founder_journey',
      },
      {
        id: 'trend_founder_confession',
        title: '🚀 "I Built This In 2 Weeks To Save My SaaS"',
        platform: 'Build In Public & Indie Hackers #1',
        viewsMetric: '7.6M Views (Live Trend)',
        velocity: '15.8% Conversion to Free Trial',
        soundtrack: 'Inspiring Ambient Future Bass',
        soundtrackId: 'reels_audio_839201',
        category: 'split_demo',
        hookFormula: 'I was literally two weeks away from shutting down my startup because [PAIN_POINT] took four hours every single day. So I built [PRODUCT_NAME], and now it creates viral reels in one click.',
        previewThumbnail: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80',
        trendingHashtags: ['#buildinpublic', '#indiehackers', '#solopreneur', '#founderstory'],
        soundBpm: 126,
        retentionScore: 96,
        viralAngle: 'founder_journey',
      },
    ];

    return NextResponse.json({
      success: true,
      lastUpdated: new Date().toISOString(),
      trendingCount: liveTrendingData.length,
      trends: liveTrendingData,
    });
  } catch (error: any) {
    console.error('Error fetching live trending reels:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to fetch live trends' },
      { status: 500 }
    );
  }
}
